export const countryList = [
	{
		"cntryCd":"AF",
		"cntryNm":"Afghanistan",
		"defaultCountry":false
	},
	{
		"cntryCd":"DZ",
		"cntryNm":"Algeria",
		"defaultCountry":false
	},
	{
		"cntryCd":"AO",
		"cntryNm":"Angola",
		"defaultCountry":false
	},
	{
		"cntryCd":"AI",
		"cntryNm":"Anguilla",
		"defaultCountry":false
	},
	{
		"cntryCd":"AG",
		"cntryNm":"Antigua",
		"defaultCountry":false
	},
	{
		"cntryCd":"AR",
		"cntryNm":"Argentina",
		"defaultCountry":false
	},
	{
		"cntryCd":"AW",
		"cntryNm":"Aruba",
		"defaultCountry":false
	},
	{
		"cntryCd":"AU",
		"cntryNm":"Australia",
		"defaultCountry":false
	},
	{
		"cntryCd":"AT",
		"cntryNm":"Austria",
		"defaultCountry":false
	},
	{
		"cntryCd":"BS",
		"cntryNm":"Bahamas",
		"defaultCountry":false
	},
	{
		"cntryCd":"BH",
		"cntryNm":"Bahrain",
		"defaultCountry":false
	},
	{
		"cntryCd":"BD",
		"cntryNm":"Bangladesh",
		"defaultCountry":false
	},
	{
		"cntryCd":"BB",
		"cntryNm":"Barbados",
		"defaultCountry":false
	},
	{
		"cntryCd":"BE",
		"cntryNm":"Belgium",
		"defaultCountry":false
	},
	{
		"cntryCd":"BZ",
		"cntryNm":"Belize",
		"defaultCountry":false
	},
	{
		"cntryCd":"BJ",
		"cntryNm":"Benin",
		"defaultCountry":false
	},
	{
		"cntryCd":"BM",
		"cntryNm":"Bermuda",
		"defaultCountry":false
	},
	{
		"cntryCd":"BT",
		"cntryNm":"Bhutan",
		"defaultCountry":false
	},
	{
		"cntryCd":"BO",
		"cntryNm":"Bolivia",
		"defaultCountry":false
	},
	{
		"cntryCd":"BQ",
		"cntryNm":"Bonaire",
		"defaultCountry":false
	},
	{
		"cntryCd":"BW",
		"cntryNm":"Botswana",
		"defaultCountry":false
	},
	{
		"cntryCd":"BR",
		"cntryNm":"Brazil",
		"defaultCountry":false
	},
	{
		"cntryCd":"BN",
		"cntryNm":"Brunei",
		"defaultCountry":false
	},
	{
		"cntryCd":"BF",
		"cntryNm":"Burkina Faso",
		"defaultCountry":false
	},
	{
		"cntryCd":"BI",
		"cntryNm":"Burundi",
		"defaultCountry":false
	},
	{
		"cntryCd":"KH",
		"cntryNm":"Cambodia",
		"defaultCountry":false
	},
	{
		"cntryCd":"CM",
		"cntryNm":"Cameroon",
		"defaultCountry":false
	},
	{
		"cntryCd":"CA",
		"cntryNm":"Canada",
		"defaultCountry":false
	},
	{
		"cntryCd":"CV",
		"cntryNm":"Cape Verde",
		"defaultCountry":false
	},
	{
		"cntryCd":"KY",
		"cntryNm":"Cayman Islands",
		"defaultCountry":false
	},
	{
		"cntryCd":"CL",
		"cntryNm":"Chile",
		"defaultCountry":false
	},
	{
		"cntryCd":"CN",
		"cntryNm":"China",
		"defaultCountry":false
	},
	{
		"cntryCd":"CO",
		"cntryNm":"Colombia",
		"defaultCountry":false
	},
	{
		"cntryCd":"CG",
		"cntryNm":"Congo",
		"defaultCountry":false
	},
	{
		"cntryCd":"CD",
		"cntryNm":"Congo, the Republic of",
		"defaultCountry":false
	},
	{
		"cntryCd":"CR",
		"cntryNm":"Costa Rica",
		"defaultCountry":false
	},
	{
		"cntryCd":"CW",
		"cntryNm":"Curacao",
		"defaultCountry":false
	},
	{
		"cntryCd":"CY",
		"cntryNm":"Cyprus",
		"defaultCountry":false
	},
	{
		"cntryCd":"CZ",
		"cntryNm":"Czech Republic",
		"defaultCountry":false
	},
	{
		"cntryCd":"DK",
		"cntryNm":"Denmark",
		"defaultCountry":false
	},
	{
		"cntryCd":"DJ",
		"cntryNm":"Djibouti",
		"defaultCountry":false
	},
	{
		"cntryCd":"DM",
		"cntryNm":"Dominica",
		"defaultCountry":false
	},
	{
		"cntryCd":"DO",
		"cntryNm":"Dominican Republic",
		"defaultCountry":false
	},
	{
		"cntryCd":"EC",
		"cntryNm":"Ecuador",
		"defaultCountry":false
	},
	{
		"cntryCd":"EG",
		"cntryNm":"Egypt",
		"defaultCountry":false
	},
	{
		"cntryCd":"SV",
		"cntryNm":"El Salvador",
		"defaultCountry":false
	},
	{
		"cntryCd":"ER",
		"cntryNm":"Eritrea",
		"defaultCountry":false
	},
	{
		"cntryCd":"EE",
		"cntryNm":"Estonia",
		"defaultCountry":false
	},
	{
		"cntryCd":"ET",
		"cntryNm":"Ethiopia",
		"defaultCountry":false
	},
	{
		"cntryCd":"FI",
		"cntryNm":"Finland",
		"defaultCountry":false
	},
	{
		"cntryCd":"FR",
		"cntryNm":"France",
		"defaultCountry":false
	},
	{
		"cntryCd":"GF",
		"cntryNm":"French Guyana",
		"defaultCountry":false
	},
	{
		"cntryCd":"GA",
		"cntryNm":"Gabon",
		"defaultCountry":false
	},
	{
		"cntryCd":"DE",
		"cntryNm":"Germany",
		"defaultCountry":false
	},
	{
		"cntryCd":"GH",
		"cntryNm":"Ghana",
		"defaultCountry":false
	},
	{
		"cntryCd":"GD",
		"cntryNm":"Grenada",
		"defaultCountry":false
	},
	{
		"cntryCd":"GP",
		"cntryNm":"Guadeloupe",
		"defaultCountry":false
	},
	{
		"cntryCd":"GU",
		"cntryNm":"Guam",
		"defaultCountry":false
	},
	{
		"cntryCd":"GT",
		"cntryNm":"Guatemala",
		"defaultCountry":false
	},
	{
		"cntryCd":"GY",
		"cntryNm":"Guyana",
		"defaultCountry":false
	},
	{
		"cntryCd":"HT",
		"cntryNm":"Haiti",
		"defaultCountry":false
	},
	{
		"cntryCd":"HN",
		"cntryNm":"Honduras",
		"defaultCountry":false
	},
	{
		"cntryCd":"HK",
		"cntryNm":"Hong Kong SAR, China",
		"defaultCountry":false
	},
	{
		"cntryCd":"HU",
		"cntryNm":"Hungary",
		"defaultCountry":false
	},
	{
		"cntryCd":"IN",
		"cntryNm":"India",
		"defaultCountry":false
	},
	{
		"cntryCd":"ID",
		"cntryNm":"Indonesia",
		"defaultCountry":false
	},
	{
		"cntryCd":"IQ",
		"cntryNm":"Iraq",
		"defaultCountry":false
	},
	{
		"cntryCd":"IE",
		"cntryNm":"Ireland",
		"defaultCountry":false
	},
	{
		"cntryCd":"IL",
		"cntryNm":"Israel",
		"defaultCountry":false
	},
	{
		"cntryCd":"IT",
		"cntryNm":"Italy",
		"defaultCountry":false
	},
	{
		"cntryCd":"CI",
		"cntryNm":"Ivory Coast",
		"defaultCountry":false
	},
	{
		"cntryCd":"JM",
		"cntryNm":"Jamaica",
		"defaultCountry":false
	},
	{
		"cntryCd":"JP",
		"cntryNm":"Japan",
		"defaultCountry":false
	},
	{
		"cntryCd":"JO",
		"cntryNm":"Jordan",
		"defaultCountry":false
	},
	{
		"cntryCd":"KZ",
		"cntryNm":"Kazakhstan",
		"defaultCountry":false
	},
	{
		"cntryCd":"KE",
		"cntryNm":"Kenya",
		"defaultCountry":false
	},
	{
		"cntryCd":"KW",
		"cntryNm":"Kuwait",
		"defaultCountry":false
	},
	{
		"cntryCd":"KG",
		"cntryNm":"Kyrgyzstan",
		"defaultCountry":false
	},
	{
		"cntryCd":"LV",
		"cntryNm":"Latvia",
		"defaultCountry":false
	},
	{
		"cntryCd":"LB",
		"cntryNm":"Lebanon",
		"defaultCountry":false
	},
	{
		"cntryCd":"LS",
		"cntryNm":"Lesotho",
		"defaultCountry":false
	},
	{
		"cntryCd":"LR",
		"cntryNm":"Liberia",
		"defaultCountry":false
	},
	{
		"cntryCd":"LY",
		"cntryNm":"Libya",
		"defaultCountry":false
	},
	{
		"cntryCd":"LT",
		"cntryNm":"Lithuania",
		"defaultCountry":false
	},
	{
		"cntryCd":"LU",
		"cntryNm":"Luxembourg",
		"defaultCountry":false
	},
	{
		"cntryCd":"MO",
		"cntryNm":"Macau SAR, China",
		"defaultCountry":false
	},
	{
		"cntryCd":"MG",
		"cntryNm":"Madagascar",
		"defaultCountry":false
	},
	{
		"cntryCd":"MW",
		"cntryNm":"Malawi",
		"defaultCountry":false
	},
	{
		"cntryCd":"MY",
		"cntryNm":"Malaysia",
		"defaultCountry":false
	},
	{
		"cntryCd":"MV",
		"cntryNm":"Maldives",
		"defaultCountry":false
	},
	{
		"cntryCd":"MQ",
		"cntryNm":"Martinique",
		"defaultCountry":false
	},
	{
		"cntryCd":"MU",
		"cntryNm":"Mauritius",
		"defaultCountry":false
	},
	{
		"cntryCd":"MX",
		"cntryNm":"Mexico",
		"defaultCountry":false
	},
	{
		"cntryCd":"MS",
		"cntryNm":"Montserrat",
		"defaultCountry":false
	},
	{
		"cntryCd":"MA",
		"cntryNm":"Morocco",
		"defaultCountry":false
	},
	{
		"cntryCd":"MZ",
		"cntryNm":"Mozambique",
		"defaultCountry":false
	},
	{
		"cntryCd":"NA",
		"cntryNm":"Namibia",
		"defaultCountry":false
	},
	{
		"cntryCd":"NP",
		"cntryNm":"Nepal",
		"defaultCountry":false
	},
	{
		"cntryCd":"NL",
		"cntryNm":"Netherlands",
		"defaultCountry":false
	},
	{
		"cntryCd":"NZ",
		"cntryNm":"New Zealand",
		"defaultCountry":false
	},
	{
		"cntryCd":"NI",
		"cntryNm":"Nicaragua",
		"defaultCountry":false
	},
	{
		"cntryCd":"NG",
		"cntryNm":"Nigeria",
		"defaultCountry":false
	},
	{
		"cntryCd":"NO",
		"cntryNm":"Norway",
		"defaultCountry":false
	},
	{
		"cntryCd":"OM",
		"cntryNm":"Oman",
		"defaultCountry":false
	},
	{
		"cntryCd":"PK",
		"cntryNm":"Pakistan",
		"defaultCountry":false
	},
	{
		"cntryCd":"PA",
		"cntryNm":"Panama",
		"defaultCountry":false
	},
	{
		"cntryCd":"PY",
		"cntryNm":"Paraguay",
		"defaultCountry":false
	},
	{
		"cntryCd":"PE",
		"cntryNm":"Peru",
		"defaultCountry":false
	},
	{
		"cntryCd":"PH",
		"cntryNm":"Philippines",
		"defaultCountry":false
	},
	{
		"cntryCd":"PL",
		"cntryNm":"Poland",
		"defaultCountry":false
	},
	{
		"cntryCd":"PT",
		"cntryNm":"Portugal",
		"defaultCountry":false
	},
	{
		"cntryCd":"PR",
		"cntryNm":"Puerto Rico",
		"defaultCountry":false
	},
	{
		"cntryCd":"QA",
		"cntryNm":"Qatar",
		"defaultCountry":false
	},
	{
		"cntryCd":"RE",
		"cntryNm":"Reunion Island",
		"defaultCountry":false
	},
	{
		"cntryCd":"RU",
		"cntryNm":"Russia",
		"defaultCountry":false
	},
	{
		"cntryCd":"RW",
		"cntryNm":"Rwanda-L4",
		"defaultCountry":false
	},
	{
		"cntryCd":"SA",
		"cntryNm":"Saudia Arabia",
		"defaultCountry":false
	},
	{
		"cntryCd":"SN",
		"cntryNm":"Senegal",
		"defaultCountry":false
	},
	{
		"cntryCd":"SC",
		"cntryNm":"Seychelles",
		"defaultCountry":false
	},
	{
		"cntryCd":"SG",
		"cntryNm":"Singapore",
		"defaultCountry":false
	},
	{
		"cntryCd":"SK",
		"cntryNm":"Slovak Republic",
		"defaultCountry":false
	},
	{
		"cntryCd":"SI",
		"cntryNm":"Slovenia",
		"defaultCountry":false
	},
	{
		"cntryCd":"ZA",
		"cntryNm":"South Africa",
		"defaultCountry":false
	},
	{
		"cntryCd":"KR",
		"cntryNm":"South Korea",
		"defaultCountry":false
	},
	{
		"cntryCd":"ES",
		"cntryNm":"Spain",
		"defaultCountry":false
	},
	{
		"cntryCd":"LK",
		"cntryNm":"Sri Lanka",
		"defaultCountry":false
	},
	{
		"cntryCd":"KN",
		"cntryNm":"St Kitts and Nevis",
		"defaultCountry":false
	},
	{
		"cntryCd":"LC",
		"cntryNm":"St Lucia",
		"defaultCountry":false
	},
	{
		"cntryCd":"SX",
		"cntryNm":"St Maarten",
		"defaultCountry":false
	},
	{
		"cntryCd":"MF",
		"cntryNm":"St Martin",
		"defaultCountry":false
	},
	{
		"cntryCd":"VC",
		"cntryNm":"St Vincent",
		"defaultCountry":false
	},
	{
		"cntryCd":"SR",
		"cntryNm":"Suriname",
		"defaultCountry":false
	},
	{
		"cntryCd":"SZ",
		"cntryNm":"Swaziland",
		"defaultCountry":false
	},
	{
		"cntryCd":"SE",
		"cntryNm":"Sweden",
		"defaultCountry":false
	},
	{
		"cntryCd":"CH",
		"cntryNm":"Switzerland",
		"defaultCountry":false
	},
	{
		"cntryCd":"TW",
		"cntryNm":"Taiwan, China",
		"defaultCountry":false
	},
	{
		"cntryCd":"TZ",
		"cntryNm":"Tanzania",
		"defaultCountry":false
	},
	{
		"cntryCd":"TH",
		"cntryNm":"Thailand",
		"defaultCountry":false
	},
	{
		"cntryCd":"TG",
		"cntryNm":"Togo",
		"defaultCountry":false
	},
	{
		"cntryCd":"TT",
		"cntryNm":"Trinidad and Tobago",
		"defaultCountry":false
	},
	{
		"cntryCd":"TN",
		"cntryNm":"Tunisia",
		"defaultCountry":false
	},
	{
		"cntryCd":"TR",
		"cntryNm":"Turkey",
		"defaultCountry":false
	},
	{
		"cntryCd":"TC",
		"cntryNm":"Turks and Caicos Islands",
		"defaultCountry":false
	},
	{
		"cntryCd":"UG",
		"cntryNm":"Uganda",
		"defaultCountry":false
	},
	{
		"cntryCd":"AE",
		"cntryNm":"United Arab Emirates",
		"defaultCountry":false
	},
	{
		"cntryCd":"GB",
		"cntryNm":"United Kingdom",
		"defaultCountry":false
	},
	{
		"cntryCd":"US",
		"cntryNm":"United States",
		"defaultCountry":true
	},
	{
		"cntryCd":"UY",
		"cntryNm":"Uruguay",
		"defaultCountry":false
	},
	{
		"cntryCd":"UZ",
		"cntryNm":"Uzbekistan",
		"defaultCountry":false
	},
	{
		"cntryCd":"VE",
		"cntryNm":"Venezuela",
		"defaultCountry":false
	},
	{
		"cntryCd":"VN",
		"cntryNm":"Vietnam",
		"defaultCountry":false
	},
	{
		"cntryCd":"VG",
		"cntryNm":"Virgin Island (GB)",
		"defaultCountry":false
	},
	{
		"cntryCd":"VI",
		"cntryNm":"Virgin Islands (USA)",
		"defaultCountry":false
	},
	{
		"cntryCd":"ZM",
		"cntryNm":"Zambia",
		"defaultCountry":false
	},
	{
		"cntryCd":"ZW",
		"cntryNm":"Zimbabwe",
		"defaultCountry":false
	}
]